# theme: jekyll-theme-midnight
remote_theme: riggraz/no-style-please
title: Load-shedding Calendar ğŸ•¯ï¸
author: Christopher Mailer # name of site's author
email: christophermailer@icloud.com # email of site's author
description: Subscribable load-shedding calendars that update automagically

favicon: "candle.png"

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
